[package]
name = "sungma-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
sungma-lang = { path = "../crates/sungma-lang" }

[[bin]]
name = "document"
path = "fuzz_targets/document.rs"
test = false
doc = false
bench = false
